export const TYPES = {
  CREAR_PRODUCTO: "CREAR_PRODUCTO",
  CONSULTAR_PRODUCTO: "CONSULTAR_PRODUCTO",
  EDITAR_PRODUCTO: "EDITAR_PRODUCTO",
  ELIMINAR_PRODUCTO: "ELIMINAR_PRODUCTO",
  SIN_DATOS: "SIN_DATOS",
  //Carrito
  AGREGAR_PRODUCTO: "AGREGAR_PRODUCTO",
  ELIMINAR_UNO: "ELIMINAR_UNO",
  ELIMINAR_TODOS: "ELIMINAR_TODOS",
  LIMPIAR_CARRITO: "LIMPIAR_CARRITO",
};
